def dibujo(n):
    if n==0:
        print('')
    elif n==1:
        print('-----')
    elif n==2:
        print('  |')
        print('  |')
        print('  |')
        print('  |')
        print('  |')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==3:
        print('  _______')
        print('  |')
        print('  |')
        print('  |')
        print('  |')
        print('  |')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==4:
        print('  ________')
        print('  |       |')
        print('  |       |')
        print('  |')
        print('  |')
        print('  |')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==5:
        print('  ________')
        print('  |       |')
        print('  |       |')
        print('  |       O')
        print('  |')
        print('  |')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==6:
        print('  ________')
        print('  |       |')
        print('  |       |')
        print('  |       O')
        print('  |       |')
        print('  |')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==7:
        print('  ________')
        print('  |       |')
        print('  |       |')
        print('  |       O')
        print('  |      /|')
        print('  |')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==8:
        print('  ________')
        print('  |       |')
        print('  |       |')
        print('  |       O')
        print('  |      /|\ ')
        print('  |')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==9:
        print('  ________')
        print('  |       |')
        print('  |       |')
        print('  |       O')
        print('  |      /|\ ')
        print('  |      /')
        print('  |')
        print('  |  ')
        print('-----')
    elif n==10:
        print('  ________')
        print('  |       |')
        print('  |       |')
        print('  |       O')
        print('  |      /|\ ')
        print('  |      / \ ')
        print('  |')
        print('  |  ')
        print('-----')
